"""replace stackoverflow with leetcode username

Revision ID: 23560df0e116
Revises: 25cddc36d0ed
Create Date: 2026-07-28 09:15:41.911674+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23560df0e116'
down_revision: Union[str, None] = '25cddc36d0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leetcode_username', sa.String(length=100), nullable=True))
    op.drop_column('users', 'stackoverflow_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stackoverflow_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'leetcode_username')
    # ### end Alembic commands ###