"""add ml data columns

Revision ID: c7ce54018dc0
Revises: 132c15b229f2
Create Date: 2026-07-29 09:27:52.835523+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ce54018dc0'
down_revision: Union[str, None] = '132c15b229f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('leetcode_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('shap_values', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_scored_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_scored_at')
    op.drop_column('users', 'shap_values')
    op.drop_column('users', 'resume_text')
    op.drop_column('users', 'leetcode_data')
    op.drop_column('users', 'github_data')
    # ### end Alembic commands ###