"""add candidate profile fields

Revision ID: f25f5965a9af
Revises: d1e309821c03
Create Date: 2026-07-07 15:58:34.686959+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25f5965a9af'
down_revision: Union[str, None] = 'd1e309821c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('stackoverflow_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('resume_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('ranking_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'ranking_score')
    op.drop_column('users', 'resume_uploaded_at')
    op.drop_column('users', 'resume_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'stackoverflow_username')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'years_of_experience')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'location')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###